import { Product } from "./types";

export const PRODUCTS: Product[] = [
  { id: '1', name: 'Premium Tomatoes', category: 'Daily', price: 0, unit: 'kg', description: 'Fresh, vine-ripened organic tomatoes.', imageUrl: 'https://images.unsplash.com/photo-1518977822534-7049a61ee0c2?q=80&w=800&auto=format&fit=crop', stock: 100, sellerId: 'local-farm', rating: 4.8, localNames: ['Tamatar', 'Tomato', 'Tamato', 'Tameta', 'Tamatara'] },
  { id: '2', name: 'Potatoes', category: 'Roots', price: 0, unit: 'kg', description: 'Nutty flavor, perfect for roasting.', imageUrl: 'https://images.unsplash.com/photo-1518977673155-06f1f82c4639?q=80&w=800&auto=format&fit=crop', stock: 200, sellerId: 'local-farm', rating: 4.5, localNames: ['Aloo', 'Alu', 'Potato', 'Batata', 'Alooa'] },
  { id: '3', name: 'Red Onions', category: 'Daily', price: 0, unit: 'kg', description: 'Strong, crunchy onions for daily cooking.', imageUrl: 'https://images.unsplash.com/photo-1620612643945-e63ca9f34a81?q=80&w=800&auto=format&fit=crop', stock: 150, sellerId: 'local-farm', rating: 4.7, localNames: ['Pyaz', 'Pyaaz', 'Onion', 'Kanda', 'Eerulli', 'Vengayam'] },
  { id: '4', name: 'Fresh Spinach', category: 'Leafy', price: 0, unit: 'bunch', description: 'Crisp, nutrient-dense green leaves.', imageUrl: 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?q=80&w=800&auto=format&fit=crop', stock: 50, sellerId: 'local-farm', rating: 4.9, localNames: ['Palak', 'Paalak', 'Spinach', 'Keerai'] },
  { id: '5', name: 'Carrots', category: 'Roots', price: 0, unit: 'kg', description: 'Sweet and crunchy organic carrots.', imageUrl: 'https://images.unsplash.com/photo-1444858291040-58f756a3bea6?q=80&w=800&auto=format&fit=crop', stock: 80, sellerId: 'local-farm', rating: 4.6, localNames: ['Gajar', 'Gaajar', 'Carrot', 'Gajara'] },
  { id: '6', name: 'Cauliflower', category: 'Daily', price: 0, unit: 'piece', description: 'Firm, white cauliflower heads.', imageUrl: 'https://images.unsplash.com/photo-1510627498534-cf7c9002facc?q=80&w=800&auto=format&fit=crop', stock: 40, sellerId: 'local-farm', rating: 4.4, localNames: ['Phool Gobi', 'Gobi', 'Gobhi', 'Cauliflower'] },
  { id: '7', name: 'Green Cabbage', category: 'Leafy', price: 0, unit: 'piece', description: 'Fresh, layered green cabbage.', imageUrl: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?q=80&w=800&auto=format&fit=crop', stock: 60, sellerId: 'local-farm', rating: 4.3, localNames: ['Patta Gobi', 'Band Gobi', 'Cabbage', 'Kobi'] },
  { id: '8', name: 'Fresh Okra', category: 'Daily', price: 0, unit: 'kg', description: 'Tender lady fingers straight from the garden.', imageUrl: 'https://images.unsplash.com/photo-1622383563227-04401ab4e5ea?q=80&w=800&auto=format&fit=crop', stock: 70, sellerId: 'local-farm', rating: 4.7, localNames: ['Bhindi', 'Bindi', 'Lady Finger', 'Okra', 'Vendakkai'] },
  { id: '9', name: 'Green Chillies', category: 'Daily', price: 0, unit: '250g', description: 'Spicy and fresh green chillies.', imageUrl: 'https://images.unsplash.com/photo-1594411132644-8cb96a1e389e?q=80&w=800&auto=format&fit=crop', stock: 100, sellerId: 'local-farm', rating: 4.8, localNames: ['Hari Mirch', 'Mirch', 'Mirchi', 'Chilli', 'Chilles', 'Pacha Mulagu'] },
  { id: '10', name: 'Bell Peppers', category: 'Exotic', price: 0, unit: 'kg', description: 'Colorful mix of sweet bell peppers.', imageUrl: 'https://images.unsplash.com/photo-1566232392379-afd9298e6a46?q=80&w=800&auto=format&fit=crop', stock: 30, sellerId: 'local-farm', rating: 4.9, localNames: ['Shimla Mirch', 'Capsicum', 'Bell Pepper'] },
  { id: '11', name: 'Coriander', category: 'Herbs', price: 0, unit: 'bunch', description: 'Fragrant and fresh coriander leaves.', imageUrl: 'https://images.unsplash.com/photo-1588636906981-81d30fb4155b?q=80&w=800&auto=format&fit=crop', stock: 100, sellerId: 'local-farm', rating: 5.0, localNames: ['Dhaniya', 'Kothmir', 'Coriander', 'Malliyila'] },
  { id: '12', name: 'Bitter Gourd', category: 'Daily', price: 0, unit: 'kg', description: 'Fresh and bitter organic karela.', imageUrl: 'https://images.unsplash.com/photo-1444491741275-3747c33cc99b?q=80&w=800&auto=format&fit=crop', stock: 50, sellerId: 'local-farm', rating: 4.2, localNames: ['Karela', 'Karala', 'Bitter Gourd', 'Pavakkai'] },
  { id: '13', name: 'Eggplant', category: 'Daily', price: 0, unit: 'kg', description: 'Small purple eggplants for bharta.', imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?q=80&w=800&auto=format&fit=crop', stock: 60, sellerId: 'local-farm', rating: 4.5, localNames: ['Baingan', 'Baigan', 'Bangan', 'Brinjal', 'Eggplant', 'Vangi', 'Kathirikkai'] },
  { id: '14', name: 'Fresh Ginger', category: 'Herbs', price: 0, unit: '250g', description: 'Pungent and spicy organic ginger.', imageUrl: 'https://images.unsplash.com/photo-1523920290228-4f321a939b4c?q=80&w=800&auto=format&fit=crop', stock: 90, sellerId: 'local-farm', rating: 4.8, localNames: ['Adrak', 'Adhu', 'Ginger', 'Inchi'] },
  { id: '15', name: 'Garlic', category: 'Herbs', price: 0, unit: '250g', description: 'Strong and flavorful local garlic.', imageUrl: 'https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?q=80&w=800&auto=format&fit=crop', stock: 100, sellerId: 'local-farm', rating: 4.7, localNames: ['Lahsun', 'Lasun', 'Lasan', 'Garlic', 'Veluthulli'] },
  { id: '16', name: 'Lemons', category: 'Daily', price: 0, unit: '250g', description: 'Zesty and juicy fresh lemons.', imageUrl: 'https://images.unsplash.com/photo-1590505681460-1d8f3ec187a5?q=80&w=800&auto=format&fit=crop', stock: 120, sellerId: 'local-farm', rating: 4.9, localNames: ['Nimbu', 'Limbu', 'Lemon', 'Cherunarakam'] },
  { id: '17', name: 'Green Beans', category: 'Daily', price: 0, unit: 'kg', description: 'Tender and crunchy French beans.', imageUrl: 'https://images.unsplash.com/photo-1515471204579-2baacc6ae1f1?q=80&w=800&auto=format&fit=crop', stock: 40, sellerId: 'local-farm', rating: 4.6, localNames: ['Beans', 'Fansi', 'Farasbi', 'Phali'] },
  { id: '18', name: 'Bottle Gourd', category: 'Daily', price: 0, unit: 'kg', description: 'Cool and light organic lauki.', imageUrl: 'https://images.unsplash.com/photo-1592394533824-9440e5d68530?q=80&w=800&auto=format&fit=crop', stock: 65, sellerId: 'local-farm', rating: 4.3, localNames: ['Lauki', 'Doodhi', 'Ghiya', 'Bottle Gourd', 'Sorakkai'] },
  { id: '19', name: 'Radish', category: 'Roots', price: 0, unit: 'kg', description: 'Crisp and peppery white daikon.', imageUrl: 'https://images.unsplash.com/photo-1594489428504-5c0c480a15fd?q=80&w=800&auto=format&fit=crop', stock: 55, sellerId: 'local-farm', rating: 4.4, localNames: ['Mooli', 'Muli', 'Radish', 'Mullangi'] },
  { id: '20', name: 'Cucumber', category: 'Fruits', price: 0, unit: 'kg', description: 'Cooling and crunchy garden cucumbers.', imageUrl: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?q=80&w=800&auto=format&fit=crop', stock: 90, sellerId: 'local-farm', rating: 4.7, localNames: ['Kheera', 'Kakdi', 'Cucumber', 'Vellarikka'] },
  { id: '21', name: 'Pumpkin', category: 'Daily', price: 0, unit: 'kg', description: 'Sweet and versatile orange pumpkin.', imageUrl: 'https://images.unsplash.com/photo-1506815444479-bfdb1e96c566?q=80&w=800&auto=format&fit=crop', stock: 50, sellerId: 'local-farm', rating: 4.4, localNames: ['Kaddu', 'Kohala', 'Pumpkin', 'Mathanga'] },
  { id: '22', name: 'Fenugreek Leaves', category: 'Leafy', price: 0, unit: 'bunch', description: 'Aromatic and slightly bitter fresh methi.', imageUrl: 'https://images.unsplash.com/photo-1548029960-695d127fdd50?q=80&w=800&auto=format&fit=crop', stock: 70, sellerId: 'local-farm', rating: 4.8, localNames: ['Methi', 'Meti', 'Fenugreek'] },
  { id: '23', name: 'Pointed Gourd', category: 'Daily', price: 0, unit: 'kg', description: 'Small, striped summer gourd.', imageUrl: 'https://images.unsplash.com/photo-1628155232233-38819b87893d?q=80&w=800&auto=format&fit=crop', stock: 50, sellerId: 'local-farm', rating: 4.2, localNames: ['Parwal', 'Parval', 'Potala'] },
  { id: '24', name: 'Ridged Gourd', category: 'Daily', price: 0, unit: 'kg', description: 'Long green gourd with ridges.', imageUrl: 'https://images.unsplash.com/photo-1594533036625-780c65538eec?q=80&w=800&auto=format&fit=crop', stock: 60, sellerId: 'local-farm', rating: 4.3, localNames: ['Turai', 'Turiya', 'Ridge Gourd', 'Peechinga'] },
  { id: '25', name: 'Sweet Potato', category: 'Roots', price: 0, unit: 'kg', description: 'Sweet and starchy orange tubers.', imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=800&auto=format&fit=crop', stock: 80, sellerId: 'local-farm', rating: 4.6, localNames: ['Shakarkand', 'Ratalu', 'Sweet Potato', 'Cheeni Kizhangu'] },
];

export const MANDI_RATES = [
  { vegetableName: 'Tomato', currentPrice: 42, previousPrice: 38, trend: 'rising', aiInsight: 'Demand surging due to local festival' },
  { vegetableName: 'Potato', currentPrice: 28, previousPrice: 30, trend: 'falling', aiInsight: 'New harvest arrivals from Punjab' },
  { vegetableName: 'Onion', currentPrice: 35, previousPrice: 35, trend: 'stable', aiInsight: 'Buffer stocks keeping prices in check' },
  { vegetableName: 'Spinach', currentPrice: 15, previousPrice: 20, trend: 'falling', aiInsight: 'Hyperlocal supply excess detected' },
  { vegetableName: 'Cauliflower', currentPrice: 45, previousPrice: 40, trend: 'rising', aiInsight: 'Seasonal transition affecting yield' },
];
