import { Product } from "./types";
import { getVegetableImage } from "./lib/imageMapping";

export const PRODUCTS: Product[] = [
  { id: '1', name: 'Premium Tomatoes', category: 'Daily', price: 45, unit: 'kg', description: 'Fresh, vine-ripened organic tomatoes.', imageUrl: getVegetableImage('Premium Tomatoes'), stock: 100, sellerId: 'local-farm', rating: 4.8, localNames: ['Tamatar', 'Tomato', 'Tamato', 'Tameta', 'Tamatara'], freshnessScore: 98, arrivedOn: new Date().toISOString(), isFreshArrivedToday: true },
  { id: '2', name: 'Potatoes', category: 'Roots', price: 30, unit: 'kg', description: 'Nutty flavor, perfect for roasting.', imageUrl: getVegetableImage('Potatoes'), stock: 200, sellerId: 'local-farm', rating: 4.5, localNames: ['Aloo', 'Alu', 'Potato', 'Batata', 'Alooa'], freshnessScore: 95, arrivedOn: new Date().toISOString(), isFreshArrivedToday: true },
  { id: '3', name: 'Red Onions', category: 'Daily', price: 35, unit: 'kg', description: 'Strong, crunchy onions for daily cooking.', imageUrl: getVegetableImage('Red Onions'), stock: 150, sellerId: 'local-farm', rating: 4.7, localNames: ['Pyaz', 'Pyaaz', 'Onion', 'Kanda', 'Eerulli', 'Vengayam'], freshnessScore: 92, arrivedOn: new Date().toISOString(), isFreshArrivedToday: false },
  { id: '4', name: 'Fresh Spinach', category: 'Leafy', price: 20, unit: 'bunch', description: 'Crisp, nutrient-dense green leaves.', imageUrl: getVegetableImage('Fresh Spinach'), stock: 50, sellerId: 'local-farm', rating: 4.9, localNames: ['Palak', 'Paalak', 'Spinach', 'Keerai'], freshnessScore: 100, arrivedOn: new Date().toISOString(), isFreshArrivedToday: true },
  { id: '5', name: 'Carrots', category: 'Roots', price: 60, unit: 'kg', description: 'Sweet and crunchy organic carrots.', imageUrl: getVegetableImage('Carrots'), stock: 80, sellerId: 'local-farm', rating: 4.6, localNames: ['Gajar', 'Gaajar', 'Carrot', 'Gajara'], freshnessScore: 94, arrivedOn: new Date().toISOString(), isFreshArrivedToday: false },
  { id: '6', name: 'Cauliflower', category: 'Daily', price: 50, unit: 'piece', description: 'Firm, white cauliflower heads.', imageUrl: getVegetableImage('Cauliflower'), stock: 40, sellerId: 'local-farm', rating: 4.4, localNames: ['Phool Gobi', 'Gobi', 'Gobhi', 'Cauliflower'], freshnessScore: 90, arrivedOn: new Date().toISOString(), isFreshArrivedToday: true },
  { id: '7', name: 'Green Cabbage', category: 'Leafy', price: 40, unit: 'piece', description: 'Fresh, layered green cabbage.', imageUrl: getVegetableImage('Green Cabbage'), stock: 60, sellerId: 'local-farm', rating: 4.3, localNames: ['Patta Gobi', 'Band Gobi', 'Cabbage', 'Kobi'], freshnessScore: 88, arrivedOn: new Date().toISOString(), isFreshArrivedToday: false },
  { id: '8', name: 'Fresh Okra', category: 'Daily', price: 40, unit: 'kg', description: 'Tender lady fingers straight from the garden.', imageUrl: getVegetableImage('Fresh Okra'), stock: 70, sellerId: 'local-farm', rating: 4.7, localNames: ['Bhindi', 'Bindi', 'Lady Finger', 'Okra', 'Vendakkai'], freshnessScore: 96, arrivedOn: new Date().toISOString(), isFreshArrivedToday: true },
  { id: '9', name: 'Green Chillies', category: 'Daily', price: 20, unit: '250g', description: 'Spicy and fresh green chillies.', imageUrl: getVegetableImage('Green Chillies'), stock: 100, sellerId: 'local-farm', rating: 4.8, localNames: ['Hari Mirch', 'Mirch', 'Mirchi', 'Chilli', 'Chilles', 'Pacha Mulagu'], freshnessScore: 95, arrivedOn: new Date().toISOString(), isFreshArrivedToday: true },
  { id: '10', name: 'Bell Peppers', category: 'Exotic', price: 120, unit: 'kg', description: 'Colorful mix of sweet bell peppers.', imageUrl: getVegetableImage('Bell Peppers'), stock: 30, sellerId: 'local-farm', rating: 4.9, localNames: ['Shimla Mirch', 'Capsicum', 'Bell Pepper'], freshnessScore: 92, arrivedOn: new Date().toISOString(), isFreshArrivedToday: false },
  { id: '11', name: 'Coriander', category: 'Herbs', price: 10, unit: 'bunch', description: 'Fragrant and fresh coriander leaves.', imageUrl: getVegetableImage('Coriander'), stock: 100, sellerId: 'local-farm', rating: 5.0, localNames: ['Dhaniya', 'Kothmir', 'Coriander', 'Malliyila'], freshnessScore: 100, arrivedOn: new Date().toISOString(), isFreshArrivedToday: true },
  { id: '12', name: 'Bitter Gourd', category: 'Daily', price: 40, unit: 'kg', description: 'Fresh and bitter organic karela.', imageUrl: getVegetableImage('Bitter Gourd'), stock: 50, sellerId: 'local-farm', rating: 4.2, localNames: ['Karela', 'Karala', 'Bitter Gourd', 'Pavakkai'], freshnessScore: 85, arrivedOn: new Date().toISOString(), isFreshArrivedToday: false },
  { id: '13', name: 'Eggplant', category: 'Daily', price: 40, unit: 'kg', description: 'Small purple eggplants for bharta.', imageUrl: getVegetableImage('Eggplant'), stock: 60, sellerId: 'local-farm', rating: 4.5, localNames: ['Baingan', 'Baigan', 'Bangan', 'Brinjal', 'Eggplant', 'Vangi', 'Kathirikkai'], freshnessScore: 91, arrivedOn: new Date().toISOString(), isFreshArrivedToday: true },
  { id: '14', name: 'Fresh Ginger', category: 'Herbs', price: 30, unit: '250g', description: 'Pungent and spicy organic ginger.', imageUrl: getVegetableImage('Fresh Ginger'), stock: 90, sellerId: 'local-farm', rating: 4.8, localNames: ['Adrak', 'Adhu', 'Ginger', 'Inchi'], freshnessScore: 98, arrivedOn: new Date().toISOString(), isFreshArrivedToday: true },
  { id: '15', name: 'Garlic', category: 'Herbs', price: 50, unit: '250g', description: 'Strong and flavorful local garlic.', imageUrl: getVegetableImage('Garlic'), stock: 100, sellerId: 'local-farm', rating: 4.7, localNames: ['Lahsun', 'Lasun', 'Lasan', 'Garlic', 'Veluthulli'], freshnessScore: 97, arrivedOn: new Date().toISOString(), isFreshArrivedToday: false },
  { id: '16', name: 'Lemons', category: 'Daily', price: 40, unit: '250g', description: 'Zesty and juicy fresh lemons.', imageUrl: getVegetableImage('Lemons'), stock: 120, sellerId: 'local-farm', rating: 4.9, localNames: ['Nimbu', 'Limbu', 'Lemon', 'Cherunarakam'], freshnessScore: 99, arrivedOn: new Date().toISOString(), isFreshArrivedToday: true },
  { id: '17', name: 'Green Beans', category: 'Daily', price: 60, unit: 'kg', description: 'Tender and crunchy French beans.', imageUrl: getVegetableImage('Green Beans'), stock: 40, sellerId: 'local-farm', rating: 4.6, localNames: ['Beans', 'Fansi', 'Farasbi', 'Phali'], freshnessScore: 90, arrivedOn: new Date().toISOString(), isFreshArrivedToday: false },
  { id: '18', name: 'Bottle Gourd', category: 'Daily', price: 35, unit: 'kg', description: 'Cool and light organic lauki.', imageUrl: getVegetableImage('Bottle Gourd'), stock: 65, sellerId: 'local-farm', rating: 4.3, localNames: ['Lauki', 'Doodhi', 'Ghiya', 'Bottle Gourd', 'Sorakkai'], freshnessScore: 93, arrivedOn: new Date().toISOString(), isFreshArrivedToday: true },
  { id: '19', name: 'Radish', category: 'Roots', price: 30, unit: 'kg', description: 'Crisp and peppery white daikon.', imageUrl: getVegetableImage('Radish'), stock: 55, sellerId: 'local-farm', rating: 4.4, localNames: ['Mooli', 'Muli', 'Radish', 'Mullangi'], freshnessScore: 89, arrivedOn: new Date().toISOString(), isFreshArrivedToday: false },
  { id: '20', name: 'Cucumber', category: 'Fruits', price: 40, unit: 'kg', description: 'Cooling and crunchy garden cucumbers.', imageUrl: getVegetableImage('Cucumber'), stock: 90, sellerId: 'local-farm', rating: 4.7, localNames: ['Kheera', 'Kakdi', 'Cucumber', 'Vellarikka'], freshnessScore: 96, arrivedOn: new Date().toISOString(), isFreshArrivedToday: true },
  { id: '21', name: 'Pumpkin', category: 'Daily', price: 30, unit: 'kg', description: 'Sweet and versatile orange pumpkin.', imageUrl: getVegetableImage('Pumpkin'), stock: 50, sellerId: 'local-farm', rating: 4.4, localNames: ['Kaddu', 'Kohala', 'Pumpkin', 'Mathanga'], freshnessScore: 87, arrivedOn: new Date().toISOString(), isFreshArrivedToday: false },
  { id: '22', name: 'Fenugreek Leaves', category: 'Leafy', price: 15, unit: 'bunch', description: 'Aromatic and slightly bitter fresh methi.', imageUrl: getVegetableImage('Fenugreek Leaves'), stock: 70, sellerId: 'local-farm', rating: 4.8, localNames: ['Methi', 'Meti', 'Fenugreek'], freshnessScore: 100, arrivedOn: new Date().toISOString(), isFreshArrivedToday: true },
  { id: '23', name: 'Pointed Gourd', category: 'Daily', price: 50, unit: 'kg', description: 'Small, striped summer gourd.', imageUrl: getVegetableImage('Pointed Gourd'), stock: 50, sellerId: 'local-farm', rating: 4.2, localNames: ['Parwal', 'Parval', 'Potala'], freshnessScore: 86, arrivedOn: new Date().toISOString(), isFreshArrivedToday: false },
  { id: '24', name: 'Ridged Gourd', category: 'Daily', price: 45, unit: 'kg', description: 'Long green gourd with ridges.', imageUrl: getVegetableImage('Ridged Gourd'), stock: 60, sellerId: 'local-farm', rating: 4.3, localNames: ['Turai', 'Turiya', 'Ridge Gourd', 'Peechinga'], freshnessScore: 88, arrivedOn: new Date().toISOString(), isFreshArrivedToday: true },
  { id: '25', name: 'Sweet Potato', category: 'Roots', price: 40, unit: 'kg', description: 'Sweet and starchy orange tubers.', imageUrl: getVegetableImage('Sweet Potato'), stock: 80, sellerId: 'local-farm', rating: 4.6, localNames: ['Shakarkand', 'Ratalu', 'Sweet Potato', 'Cheeni Kizhangu'], freshnessScore: 92, arrivedOn: new Date().toISOString(), isFreshArrivedToday: false },
];

export const MANDI_RATES = [
  { vegetableName: 'Tomato', currentPrice: 42, previousPrice: 38, trend: 'rising', aiInsight: 'Demand surging due to local festival' },
  { vegetableName: 'Potato', currentPrice: 28, previousPrice: 30, trend: 'falling', aiInsight: 'New harvest arrivals from Punjab' },
  { vegetableName: 'Onion', currentPrice: 35, previousPrice: 35, trend: 'stable', aiInsight: 'Buffer stocks keeping prices in check' },
  { vegetableName: 'Spinach', currentPrice: 15, previousPrice: 20, trend: 'falling', aiInsight: 'Hyperlocal supply excess detected' },
  { vegetableName: 'Cauliflower', currentPrice: 45, previousPrice: 40, trend: 'rising', aiInsight: 'Seasonal transition affecting yield' },
];
